In [1]:
import numpy as np

In [3]:
lst1=[1,2,3,4,5]
np.array(lst1)

array([1, 2, 3, 4, 5])

In [8]:
lst2=[6,7,8,9,0]
lst3=[2,4,6,8,0]
arr=np.array([lst1,lst2,lst3])
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [2, 4, 6, 8, 0]])

In [11]:
arr=arr.reshape(5,3)

In [12]:
arr[1][1]

5

In [14]:
arr=arr.reshape(3,5)
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [2, 4, 6, 8, 0]])

In [15]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [2, 4, 6, 8, 0]])

In [16]:
arr[1:,2:]

array([[8, 9, 0],
       [6, 8, 0]])

In [17]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [19]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [20]:
np.arange(0,10,step=2)

array([0, 2, 4, 6, 8])

In [22]:
np.linspace(1,50,50,dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [33]:
arr1=np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr2=arr1.copy()
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr1[3:]=100
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr1

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [41]:
v=2
arr2>v

array([False, False,  True,  True,  True,  True,  True,  True,  True])

In [42]:
arr2*v

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [44]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [46]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [47]:
np.random.rand(3,5)

array([[0.45245473, 0.00181827, 0.1924302 , 0.00264613, 0.05270793],
       [0.68150575, 0.03144785, 0.010432  , 0.50242316, 0.37677559],
       [0.49714834, 0.76071398, 0.44028405, 0.76998461, 0.12193012]])

In [48]:
np.random.randn(3,4)

array([[-0.17708726,  0.49990777,  0.82130912, -0.19307909],
       [ 0.41702506, -0.54951002, -0.89434992, -0.87043767],
       [-1.51646474,  1.2099202 ,  1.57171   ,  0.59347653]])

In [50]:
np.random.randint(0,100,20)

array([76,  5, 88,  3,  5, 90, 11, 26, 66,  1, 74, 68, 40, 20, 61, 10, 17,
       41, 54, 52])

In [51]:
np.random.randint(0,100,20).reshape(5,4)

array([[ 6,  7, 84,  7],
       [58, 78, 90,  9],
       [36, 41, 20, 29],
       [54, 70, 68, 28],
       [22,  2, 43, 50]])